### ISSUE TITLE
All Torrents Stalled

### ISSUE THREAD

**Issue by bookenout** [mafredri/asustor-qbittorrent#2]
I just updated qBittorrent to v3.3.16 and all of my downloads have been stalled. Every once in a while the torrent will try to connect again but then stalls out again. I keep getting "An I/O error occured, torrent paused, torrent error: Access is denied". I thought this might be a version issue so I rolled back to v3.3.15 - no change, then v3.3.11 - no change, then v3.3.9 - all no change in error and Stalled torrents. I haven't tried downloading anything in about a month but I haven't changed any of my settings since my last successful download other than updating qBittorrent but rolling back the version didn't help.

Can't find any post with a similar problem and most "stalled" posts I find are from years ago. Not sure what to do.

OS: Windows 10 64bit
I use a PIA proxy server and I checked that my account is in order and I'm using the correct credentials. 

Please let me know if you need any further information.

**Comment by mafredri** [comment]
> An I/O error occured, torrent paused, torrent error: Access is denied

Have you recently moved / copied files or changed permissions anywhere on your NAS? If you look at the storage path in the detail view of a torrent, can you confirm that that actual path exists?

Do you know how to SSH into the NAS? Also, did you update ADM recently?

**Comment by bookenout** [comment]
Thanks for replying! I recently realized I was posting this question to you and not on the qBittorrent board. Sorry for that, but much appreciate you helping me!

I don't have a home network. Everything is done on my one computer and no, nothing has changed. No recent updates to my OS, nothing has been moved or changed since before my last successful torrent download. I don't remove torrents until they have been completely downloaded either.

![2017-09-24_11-58-09](https://user-images.githubusercontent.com/32244288/30785851-bcab207e-a132-11e7-962f-43afb72fe2af.png)
![2017-09-24_11-45-59](https://user-images.githubusercontent.com/32244288/30785852-bcc6f75e-a132-11e7-9249-4cb4c6780e26.png)

**Comment by bookenout** [comment]
OMG... disregard my post. It was my anti-virus blocking the app. I don't know why it all of a sudden started blocking it but it did and now it's fixed. So sorry for waisting your time. Your reply did start making me think down the path that helped me find the solution so thanks a ton!!

**Comment by mafredri** [comment]
No worries, glad you found the solution! :)
